server_address = "127.0.0.1"
server_port = 3000
domain = "dskyberg"
app = "default"
session_timeouit = 1
scopes = ["email", "profile"]
amrs = ["mfa", "pwd", "user", "hwk"]
verify_aud = true
use_par = false
use_pkce = true
